const boardActionTypes = {
  BOARD_LOADING: 'BOARD_LOADING',
  GET_ALL_LISTS_SUCCESS: 'GET_ALL_LISTS_SUCCESS',
  GET_ALL_LISTS_FAIL: 'GET_ALL_LISTS_FAIL',
  UPDATE_CARD_SUCCESS: 'UPDATE_CARD_SUCCESS',
  UPDATE_CARD_FAIL: 'UPDATE_CARD_FAIL',
};

export default boardActionTypes;
